[tool.poetry]
name = "fedstats"
version = "0.1.0"
description = ""
authors = ["RaphaelRehms <rrehms@ibe.med.uni-muenchen.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
diffprivlib = "^0.6.5"
pandas = "^2.2.3"
lifelines = "^0.30.0"
numpy = "1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
